Repository dscpesu/my-first-opensource-contribution, pull requests merged in 2023-10, with the labels that each got.

#51 added adithya markdown file - Adithya S K
  my-first-opensource-contribution/contributions/adithya-s-k.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#64 Added bhavanabandi markdown - Bhavana Bandi
  my-first-opensource-contribution/contributions/bhavanabandi.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#46 added Leharaditya.mdx @Lehar
  my-first-opensource-contribution/contributions/Leharaditya.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#60 Added Varun's mdx file
  my-first-opensource-contribution/contributions/m-s-varun.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#71 docs: modified anirudhprasad.mdx
  my-first-opensource-contribution/contributions/anirudhprasad.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#61 Pull request
  my-first-opensource-contribution/contributions/ganeshv.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#9 my first contribute
  my-first-opensource-contribution/contributions/suntiparb72.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#81 Added Anirudh's markdown file
  my-first-opensource-contribution/contributions/anirudh-h-a.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#79 Updated chandana-m-s markdown file
  my-first-opensource-contribution/contributions/chandana-m-s.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#76 Added markdown file
  Surabhi-KC.md
Labels: hacktoberfest, hacktoberfest-accepted

#13 Added Rahul Baradol Markdown!
  my-first-opensource-contribution/contributions/Rahul-Baradol.mdx
  my-first-opensource-contribution/contributions/rahulbaradol.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#52 sakethvunka.mdx
  my-first-opensource-contribution/contributions/sakethvunka.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#53 added sharath-m-s markdown file - Sharath M S
  my-first-opensource-contribution/contributions/sharath-m-s.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#54 Aaryan
  my-first-opensource-contribution/contributions/aaryanbadyal.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#74 Neha's markdown
  my-first-opensource-contribution/contributions/nehasundararaman.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#77 Added mdx - Achala Nayak
  my-first-opensource-contribution/contributions/achala-nayak.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#62 Added ananth's markdown file
  my-first-opensource-contribution/contributions/swamy.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#58 added Supratik's markdown
  my-first-opensource-contribution/contributions/supratikvishnu.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#57 Added personal Markdown - Anuraag
  my-first-opensource-contribution/contributions/anuraag_srivatsa.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#56 added ankit avinash mkdn file - Ankit Avinash
  my-first-opensource-contribution/contributions/ankit-avinash.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#55 Added Bhaveen's markdown file
  my-first-opensource-contribution/contributions/Bhvaeen_Madhavan.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#449 added M-PavanPrathap markdown
  my-first-opensource-contribution/contributions/M-Pavan-Prathap.mdx
Labels: invalid

#656 Updated swamy.mdx
  my-first-opensource-contribution/contributions/swamy.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#415 added suchir-m-v.mdx file
  my-first-opensource-contribution/contributions/suchir-m-v.mdx
Labels: invalid

#651 add-eaglesight02.mdx
  eaglesight02.mdx
  my-first-opensource-contribution/contributions/eaglesight02.mdx
Labels: formatting-error
